# Generated by Django 2.1.7 on 2019-03-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, db_column='CId', max_length=10, null=True)),
                ('cname', models.CharField(blank=True, db_column='Cname', max_length=10, null=True)),
                ('tid', models.CharField(blank=True, db_column='TId', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=255, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=255, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True, db_column='SId', max_length=10, null=True)),
                ('cid', models.CharField(blank=True, db_column='CId', max_length=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'SC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True, db_column='SId', max_length=10, null=True, unique=True)),
                ('sname', models.CharField(blank=True, db_column='Sname', max_length=10, null=True)),
                ('sage', models.DateTimeField(blank=True, db_column='Sage', null=True)),
                ('ssex', models.CharField(blank=True, db_column='Ssex', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(blank=True, db_column='TId', max_length=10, null=True)),
                ('tname', models.CharField(blank=True, db_column='Tname', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Teacher',
                'managed': False,
            },
        ),
    ]
